### ISSUE TITLE
provide a harness.check task that fails when a project needs to be harnessed

### ISSUE THREAD

**Issue by the-mikedavis** [NFIBrokerage/harness#16]
slack context: https://cuatrohq.slack.com/archives/C01AY5REC9X/p1614806484026700

idea is that a run of `mix harness` should

1. read the manifest
2. hash the keyword list produced by that read
3. write it to a file in `.harness`

and then we can provide a task `mix harness.check` which

1. checks for that file (`.harness/.manifesthash` or whatever)
2. reads the manifest and hashes it
3. compare the hash in the hashfile with the hash of the manifest
4. ifneq, fail with a helpful message
5. ifeq, no output, successful exit code

ideally this info would go in the `harness.lock` but right now that file is entirely managed through mix tasks by pushing a fake project onto the project stack with `harness.lock` as the lockfile

this feature would allow one to gate other mix tasks on their .harness directory being up to date, e.g.

```elixir
# mix.exs

def aliases do
  [
    test: ["harness.check", "test"]
  ]
end
```

so that you cannot run tests if your .harness dir is out of date

**Comment by the-mikedavis** [comment]
as for the hashing function I think the [broadway docs](https://hexdocs.pm/broadway/Broadway.html#module-ordering-and-partitioning) mention [`:erlang.phash2/1`](http://erlang.org/doc/man/erlang.html#phash2-1) which works quite portably across erts'

**Comment by the-mikedavis** [comment]
@tonyvanriet any chance you want this one? I can take care of it otherwise (if you know what I mean)

**Comment by tonyvanriet** [comment]
attractive, thx for askin, but no, I don't think I'd get to put attention on it too soon.
don't wait for me!
