### ISSUE TITLE
Example harness package?

### ISSUE THREAD

**Issue by forest** [NFIBrokerage/harness#21]
I stumbled into harness and it looks to solve problems we have as well./

Do you have an example harness package and how it is used you can point me too?

Thanks.

**Comment by the-mikedavis** [comment]
I just made this package we used in the past public: https://github.com/NFIBrokerage/harness_dotfiles

We ended up moving away from using a harness package just for dotfiles (towards more specific, larger packages that cover everything), but I think it serves as a nice minimal example. Unfortunately these packages are usually subject to a lot of internal discussion and assumptions about architecture / best practices that I don't think is super suitable to be open sourced, so I'm not sure I can open up the ones we currently use.

I'll push a documentation change that will close this out but please feel free to continue the discussion / ask questions 😀

**Comment by forest** [comment]
Awesome. Thanks for the guidance.
